### ISSUE TITLE
Doesn't check for dependency on expat dev during make

### ISSUE THREAD

**Issue by pparkkin** [harisekhon/lib#11]
When I try to `make` on Ubuntu 14.04, I get the following error.

    Expat.xs:12:19: fatal error: expat.h: No such file or directory
     #include <expat.h>
                       ^

Probably want to check for the dependency.

**Comment by harisekhon** [comment]
@pparkkin

Thanks for raising this. I had that dep specified only for RHEL based minimal-install systems but have just added what should be the ubuntu equivalent package ```libexpat1-dev``` as well.

Please git pull and try again.

**Comment by pparkkin** [comment]
Works. Thanks!

**Comment by harisekhon** [comment]
Cool, thanks for confirming - I'll close this ticket.
