### ISSUE TITLE
Missing openssl include when building library.

### ISSUE THREAD

**Issue by pparkkin** [harisekhon/lib#13]
Got error building the library:

    openssl-version.c:2:30: fatal error: openssl/opensslv.h: No such file or directory
     #include <openssl/opensslv.h>

Ubuntu 14.04.2 LTS

**Comment by harisekhon** [comment]
@pparkkin 

You don't have the openssl development libraries installed. Try doing

```apt-get install libssl-dev```

and then run make again.

**Comment by pparkkin** [comment]
That is what we're doing right now, and it works fine. Just wanted to report this to you in case you want to add it to your Makefile where you install dependencies, or the README.

**Comment by harisekhon** [comment]
I've added it to the list of deb packages, thanks.
