### ISSUE TITLE
Add SSL and auth support for Elasticsearch checks

### ISSUE THREAD

**Issue by jzheaux** [HariSekhon/lib#18]
Great library! Any plans to make so that the elasticsearch checks can go over SSL for folks who are using the Shield plugin?

**Comment by koma85** [comment]
+1 to that!

**Comment by HariSekhon** [comment]
I will definitely do this, it's not hard to so as I do this for a lot of other technologies, but right now I'm just stretched on time so it'll be a little while.

**Comment by HariSekhon** [comment]
Been so busy but thanks to @ted3 pull request #24 addresses this so closing.
