### ISSUE TITLE
Simple Instructions?

### ISSUE THREAD

**Issue by inscrutabledude** [HariSekhon/lib#21]
Hi,

I wanted to use your elasticsearch and couchbase plugins.  Which seem to require your perl lib etc.  I don't need or want any hadoop stuff etc, nor do I want to clone the entire library of plugins onto my server.

I apologize for being a noob with perl and git, but how can I simply get the prereqs and the specific plugins that I want to work on my system?

check_elasticsearch.pl required HariSekhonUtils.pm which in turn is looking for JSON.pm, which I don't see in your repo.  So like the title says, do you have some simple instructions so I can get these plugins running on Nagios?

Thanks in advance for any help you can offer.

**Comment by HariSekhon** [comment]
The project is designed to be one complete thing, like a Linux core utils or an apache software project you don't usually copy some bits and not others, it's easier to just copy the whole thing and it takes hardly any space anyway by modern standards, it's inefficient to try to be too efficient.

The `make perl-libs` will give you just the minimum for the perl plugins to run ignoring the python ones.

**Comment by inscrutabledude** [comment]
fatal: Unable to mark file resources/custom_tlds.txt
make: *** [build] Error 128
 I also tried make perl-libs but got "make: *** No rule to make target `perl-libs'.  Stop."

Any advice appreciated.

**Comment by inscrutabledude** [comment]
Ok, I sorted out thos problems.  Now I'm getting files that are just missing:

CRITICAL: Can't locate Sub/Util.pm in @INC (@INC contains: /usr/local/lib64/perl5/HariSekhon/
