### ISSUE TITLE
allow username as all numeric

### ISSUE THREAD

**Issue by pdaugavietis** [HariSekhon/lib#23]
our usernames are fully numeric and that's failing (i'm guessing) your username regex, which needs to have leading alpha?

**Comment by HariSekhon** [comment]
@pdaugavietis 

Thanks very much for raising this. Ironically I raised this exact issue a few months back for a more widely used Apache project just a few months back when working for a client with all numeric usernames and didn't realise my own libraries were also too strict on this point.

I've updated this library, the accompanying unit tests and all the dependent github projects.

Hopefull this should sort your issue.

Cheers

Hari

**Comment by HariSekhon** [comment]
Closing as this was fixed yesterday, please re-open if needed.
