### ISSUE TITLE
ElasticSearch --ssl-noverify fails with CRITICAL: 500 SSL_verify_mode must be a number and not a string

### ISSUE THREAD

**Issue by ted3** [HariSekhon/lib#37]
this bug is occurring with later versions of centos/perl/lwp where lwp ssl verification parameters have changed and a slightly different format is required for skipping verification to work. CentOS 6.3 and older versions aren't having any issues, but 6.9 and later (or equivalents in other distros) will break if skipping ssl certificate or hostname verification is required

**Comment by ArcticSnowman** [comment]
Latest docker download give me this error...

```querying Elasticsearch
HTTP GET https://es.example.com:9200/?pretty=true
returned HTML:

Can't verify SSL peers without knowing which Certificate Authorities to trust

This problem can be fixed by either setting the PERL_LWP_SSL_CA_FILE
environment variable or by installing the Mozilla::CA module.

To disable verification of SSL peers set the PERL_LWP_SSL_VERIFY_HOSTNAME
environment variable to 0.  If you do this you can't be sure that you
communicate with the expected peer.

```

**Comment by HariSekhon** [comment]
PR #38 has been merged, thanks.
