### ISSUE TITLE
mac_regex error

### ISSUE THREAD

**Issue by ronan360** [HariSekhon/lib#41]
Hi,

I think there is a mistake in mac_regex.
The first block is [0-9A-F-af] and should be [0-9A-Fa-f]

https://github.com/HariSekhon/lib/blob/3000c47f649677d4975bfb0cc03d82cfe6a9d6b4/HariSekhonUtils.pm#L700

Thank you

**Comment by HariSekhon** [comment]
Thanks very much for the spot! Yes minor typo, fixed.
