### ISSUE TITLE
aws secret key

### ISSUE THREAD

**Issue by jwojcik** [harisekhon/lib#7]
The aws secret key is not necessarily alphanumeric. My suggestion is to remove the alphanum check, or go with the aws recommended regex. However, amazon says this is also subject to change.

From http://blogs.aws.amazon.com/security/blog/tag/key+rotation

"·  Search for access key IDs: (?<![A-Z0-9])[A-Z0-9]{20}(?![A-Z0-9]).  In English, this regular expression says: Find me 20-character, uppercase, alphanumeric strings that don’t have any uppercase, alphanumeric characters immediately before or after.

·  Search for secret access keys: (?<![A-Za-z0-9/+=])[A-Za-z0-9/+=]{40}(?![A-Za-z0-9/+=]).  In English, this regular expression says: Find me 40-character, base-64 strings that don’t have any base 64 characters immediately before or after."

"We can’t guarantee these regular expressions will work forever (we reserve the right to change the format of access key IDs and secret access keys) but they’re a start."

**Comment by harisekhon** [comment]
I've just updated the aws regex validation, thanks very much for pointing this out.

**Comment by jwojcik** [comment]
Thank you!
