### ISSUE TITLE
Hostnames starting with numbers: 1.example.com

### ISSUE THREAD

**Issue by FrankGruellich** [harisekhon/lib#9]
Hi,

check_ssl_cert.pl does not like my hostname:

    % ./check_ssl_cert.pl --host 1.example.com |head -n3
    invalid host '1.example.com' defined: not a valid hostname or IP address
    
    usage: check_ssl_cert.pl [ options ]
    % 

The regex hostnames are matched against expects them to start with letters ([A-Za-z]).  However, numbers in hostnames are perfectly valid.

Kind regards,
 Frank.

**Comment by harisekhon** [comment]
I've updated the nagios-plugins to use the newer lib, that should work now, you can reopen if needed.
